spring.application.name=IT211-ProjectFinal

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/IT211_ProjectFinal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=21012005

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
